# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vuxy7TO94YTwibqWdvBQPGUqaSzOj9dE
"""

#CALCULADORA  BRUNO DA SILVA SANTOS
continuar=1

print('CALCULADORA')
while continuar!=0:

  print('\nSELECIONE UMA OPÇÃO:\n')
  print('1 - soma')
  print('\n2 - subtraçao')
  print('\n3 - multiplicação')
  print('\n4 - divisão')
  print('\n5 - potenciação')
  print('\n0 - Sair')

  valorDigitado=(input('Digite sua opção : '))
  verifica=valorDigitado.isnumeric()
  if verifica==False:
    print('Digite apenas números. Tente novamente"')
    continuar=1
  elif verifica==True:
    opcao=int(valorDigitado)
    continuar=1
    verifica=False
    if opcao==0:
      continuar=0
      print('Fim do progama')
      break
    elif (opcao>5) and (opcao!=0):
      print('OPÇÃO INVÁLIDA. DIGITE NOVAMENTE!')
      continuar=1
    else:
      while verifica==False:
        valorDigitado=input('Digite um número: ')
        verifica=valorDigitado.isnumeric()
        if verifica==False:
          print('DIGITE APENAS NUMEROS')
          continuar=1
        elif verifica==True:
          n1=float(valorDigitado)
          verifica=False
          while verifica==False:
            valorDigitado=input('Digite outro número: ')
            verifica=valorDigitado.isnumeric()
            if verifica==False:
              print('Digite apenas números! tente novamente')
              continuar=1
            else:
              n2=float(valorDigitado)
              continuar=1
              if opcao==1:
                resultado=n1+n2
                continuar=1
                print('RESULTADO: ',n1,'+', n2, "=", resultado)
              elif opcao==2:
                resultado=n1-n2
                continuar=1
                print('RESULTADO: ', n1,'-', n2, "=", resultado)
              elif opcao==3:
                resultado=n1*n2
                continuar=1
                print('RESULTADO: ', n1,'x', n2, "=", resultado)
              elif opcao==4:
                if n2==0:
                  print('NÃO É POSSIVEL DIVIDIR POR ZERO')
                  continuar=1
                else:
                  resultado=n1/n2
                  continuar=1
                  print('RESULTADO: ', n1,'/', n2, "=", resultado)
              elif opcao==5:
                resultado=n1**n2
                print('RESULTADO: ', n1,'elevado a', n2, "=", resultado)
                continuar=1
              else:
                print('ERRO INESPERADO!')
                continuar=0
                break