#!/bin/bash




echo "ESSE PROGRAMA REALIZA CADASTRO DE USUARIO, GERA RELATORIO COM A MEDIA DE IDADE DOS USUÁRIOS, CRIA GRÁFICO E INICIA UMA CALCULADORA EM PYTHON"

echo "INSTALA E ATUALIZA O PYTHON 3 E O GNUPLOT"
./config.sh

echo "FIM DAS CONFIGURAÇÕES!"

echo "FAÇA SEU CADASTRO PARA INICIAR O PROGRAMA"
./cadastro.sh

echo "INICIANDO CALCULADORA PYTHON!"

python3 calculadora.py

echo "RELATÓRIO DE USUARIOS"
./leDados.sh

echo "GRAFICO GERADO COM SUCESSO"


